### ISSUE TITLE
Can't find ngx-summernote module after npm install and ng serve 

### ISSUE THREAD

**Issue by raydvard** [lula/ngx-summernote#1]
Can't open the demo project, It says `can't find ngx-summernote module` in app.module.ts

In package.json using -
summernote: version

In node_modules -
summernote library exists.

**Comment by lula** [comment]
I'm assuming you cloned the repo. Did you build the lib before running `ng serve`? The repo is built with angular-cli so you have to build the lib before you it can be used in the demo project.

**Comment by Naveed1842** [comment]
I'm trying to use the ngx-summer note as npm.First I try to 
1:npm using npm  install --save summernote ngx-summernote
2:I try to import the modules into desired module as well.
3:When I used it as component it gave an error $ is not summer-note function

**Comment by lula** [comment]
Have you added jquery in angular.json?

```
"styles": [
  ...
  "node_modules/summernote/dist/summernote-lite.css"
],
"scripts": [
  ...
  "node_modules/jquery/dist/jquery.min.js",
  "node_modules/summernote/dist/summernote-lite.js"
]
```

**Comment by zohaibjawaid92** [comment]
have anyone implemented summernote for angular7? 
mine is giving error on ngx-summernote.

**Comment by zohaibjawaid92** [comment]
@lula Please solve this issue.
