### ISSUE TITLE
In summernote select all text and change font size but only change first line other not change.

### ISSUE THREAD

**Issue by rohit64Singh222** [lula/ngx-summernote#101]
Hello, 
  I am using ngx-summernote ^0.7.7 version there is issue when select all content added in summernote and change font size, Only reflect in first line. If line have any <br> that time issue is create.

![image](https://user-images.githubusercontent.com/57747188/93343269-ed8f8e80-f84d-11ea-9d51-4778105344ac.png)

Only font change in first line.
![image](https://user-images.githubusercontent.com/57747188/93344349-3267f500-f84f-11ea-8c19-b70d88c3b9f0.png)

**Comment by rohit64Singh222** [comment]
Hello, 

     Any update ?

**Comment by rohit64Singh222** [comment]
Hello,

 Any update of this problem ?

**Comment by rohit64Singh222** [comment]
Hello, any update ?

**Comment by rohit64Singh222** [comment]
Hello,
Any update of this problem ?

**Comment by rohit64Singh222** [comment]
Hello, any Update ?

**Comment by lula** [comment]
Hello @rohit64Singh222 have you tried by using summernote only (without this lib)? Is the error not happening? I believe you should first address this issue to summernote repo. Please repoen the issue only if this error is happening because of this lib.

**Comment by rohit64Singh222** [comment]
Hello @lula 
 I am using same lib "ngx-summernote": "^0.7.7" and this issue generate.

**Comment by lula** [comment]
ngx-summernote lib is just a wrapper of [summernote](https://github.com/summernote/summernote) for Angular, so unless the problem is clearly caused by ngx-summernote lib (which I doubt in this case) you should open an issue in [summernote](https://github.com/summernote/summernote/issues) repo.

**Comment by rohit64Singh222** [comment]
@lula 
I am try in same issue generate in summernote give example. 

https://summernote.org/deep-dive/#custom-toolbar-popover

Ok then I will add same issue in summernote repo.

**Comment by jeev-33** [comment]
> @lula I am try in same issue generate in summernote give example.
> 
> https://summernote.org/deep-dive/#custom-toolbar-popover
> 
> Ok then I will add same issue in summernote repo.

Hi @rohit64Singh222 / @lula ,

With reference to the issue 'https://github.com/summernote/summernote/issues/3963' and an work-around jQuery code snippet has been provided.

I tried adding it to my ngOnInit() function but my issue is not yet resolved can anyone help me on it. I am currently stuck on it for more than a week.
