### ISSUE TITLE
How to add spell check

### ISSUE THREAD

**Issue by mayilsaran** [lula/ngx-summernote#102]
How to add spell check in the editor

**Comment by mayilsaran** [comment]
@lula ,Any help on this ,on urgent basis.

**Comment by lula** [comment]
Hello @mayilsaran sorry for delay. I guess you should address the question to summernote repo.

**Comment by lula** [comment]
Have you tried with spellCheck summernote option?

**Comment by mayilsaran** [comment]
No.How can we use summernote repo in Angular8. I am using ngxsummernote.

**Comment by lula** [comment]
well... when you installed ngx-summernote (this lib...) you also installed summernote lib. See readme. 
Anyway:

`npm install --save summernote`
