### ISSUE TITLE
No events working for ngx summernote

### ISSUE THREAD

**Issue by jagdishcodes** [lula/ngx-summernote#103]
I tried every event in ngx summernote like keypress, keydown, keyup but it is not working. I am using angular version 8.0. am I doing anything wrong?

 `<div [ngxSummernote] class="form-control" formControlName="value" (keypress)="test($event)">
                      </div>`

**Comment by lula** [comment]
Hello @jagdishcodes  

sorry for delay.

Just use summernote callbacks in options: 

```
callbacks: {
      onKeyup: (event) => {
       console.log('Keyup', event)
      }
    }
```
