### ISSUE TITLE
Backdrop

### ISSUE THREAD

**Issue by SerGem811** [lula/ngx-summernote#105]
Hi
I am using ngx-summernote, and facing problems on insert image.

![image](https://user-images.githubusercontent.com/51737539/97277429-c22e9500-1838-11eb-99b6-5bba1dce22bd.png)

Is there any solution for this one?
What i found so far is, 
```
  .note-moda {
  ....
    z-index: 1050;
  }
```
```
  .note-modal-backdrop {
    z-index: 1040;
  }
```

**Comment by lula** [comment]
Hello @SerGem811 I guess such questions should be addressed to summernote lib. Anyway I just tried with 0.8.18 and it seems to work fine:

<img width="778" alt="Screenshot 2020-11-09 at 10 51 34" src="https://user-images.githubusercontent.com/614544/98526095-a3d58a00-2279-11eb-80ad-6e4b80e155cf.png">

**Comment by SerGem811** [comment]
Just it is happening on Ionic, in mobile.
