### ISSUE TITLE
Component not displayed properly

### ISSUE THREAD

**Issue by RDevR99** [lula/ngx-summernote#106]
Expected:
![image](https://user-images.githubusercontent.com/42928792/97668587-63864700-1ad6-11eb-82cb-dc63bd99e0a4.png)

Real outcome:
![image](https://user-images.githubusercontent.com/42928792/97668514-3d60a700-1ad6-11eb-8dfd-3bf65cf830e4.png)

I have placed the css files correctly as instructed.

Console error:
![image](https://user-images.githubusercontent.com/42928792/97668842-faeb9a00-1ad6-11eb-92eb-b34225213484.png)

**Comment by lula** [comment]
Hello @RDevR99 what summernote version are you using? I just tried with the latest (0.8.18) and css is fine. All css styles are taken from the summernote lib, though, so there's not much I can do with it.

<img width="1199" alt="Screenshot 2020-11-09 at 10 48 59" src="https://user-images.githubusercontent.com/614544/98525862-5e18c180-2279-11eb-9af0-9a71deac8d29.png">
