### ISSUE TITLE
All Toolbox options

### ISSUE THREAD

**Issue by JaviLopezM** [lula/ngx-summernote#107]
I need to check all the Toolbox options, because I want to add some options but they are not in the example.
For example, a heading selector and others.

thanks.

**Comment by lula** [comment]
Hello @JaviLopezM have you checked [summernote](https://github.com/summernote/summernote/) options? You can check there all the available options, as this repo is just a wrapper for Angular.  Should you need some custom feature, you can always add a custom button.
