### ISSUE TITLE
Summernote not allowing me to paste images

### ISSUE THREAD

**Issue by ramitmathur27m** [lula/ngx-summernote#11]
Hi,

I have integrated this summernote in my Angular 7 application. It integrated smoothly but its not allowing me to paste images which i am using snipping tool of windows. Any suggestion, please help!

Thanks
Ramit

**Comment by lula** [comment]
Hello @ramitmathur27m I have no problem with pasting images:

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/614544/50185575-77789380-0318-11e9-9775-47f5b894657f.gif)

Is it what you are trying to do?

**Comment by ramitmathur27m** [comment]
Thanks for replying, really Appreciated!

Yes, i am trying the same, i am using Angular 7.0.6 and getting below warning when i am using your application as a standalone.

**warning i am getting:**
**Your global Angular CLI version (7.0.6) is greater than your local
version (6.0.8). The local Angular CLI version is used.

To disable this warning use "ng config -g cli.warnings.versionMismatch false".
** Angular Live Development Server is listening on localhost:4200, open your bro**

But never get this warning when i am integrating with my application. 
Is there any additional steps i need to take care. 

My Angular.json has these enteries:
![image](https://user-images.githubusercontent.com/12241376/50186136-e7baf100-02e7-11e9-9163-929f9a811e43.png)

Let me know if anything is getting suppressed??
 
could you please try to run ng --version at your end to see which version you are pointing.
Below is my ng version:-
![image](https://user-images.githubusercontent.com/12241376/50186010-7e3ae280-02e7-11e9-82d5-3451d6389c01.png)

Thanks
Ramit Mathur

**Comment by ramitmathur27m** [comment]
Hi,

Any clue??

**Comment by lula** [comment]
That's Angular, it has nothing to do with this lib. The error says that your local Angular CLI is older than the one you have installed globally. To use the local cli you can use npx like `npx ng build`.

**Comment by ramitmathur27m** [comment]
Tried, only problem i am facing is while pasting pics. Followed all the steps. Still cant find the exact problem b/c the same is working in standalone application however integrating with main application pasting is not working. 

Can someone help me in debugging this would be grt help.

Thanks
Ramit
