### ISSUE TITLE
Italic not working

### ISSUE THREAD

**Issue by RakZoRr0** [lula/ngx-summernote#117]
the configuration I have is:

* angular cli: 9.0.2
* node: 12.13.1
* ngx-summernote: 0.8.4

* no bootstrap

when i use italic it shows the following

![image](https://user-images.githubusercontent.com/3442944/117213279-06d75200-adc1-11eb-8e2b-02fe384c3eee.png)

and the code

![image](https://user-images.githubusercontent.com/3442944/117213300-0c349c80-adc1-11eb-8f02-378fad3898b8.png)

I don't know what is causing it

**Comment by lula** [comment]
Hello! This kind of issues should be addressed to summernote repo, I guess. Anyway, for some reasons `<p>` is always present.
