### ISSUE TITLE
Not working with Angular 7.0.6

### ISSUE THREAD

**Issue by ramitmathur27m** [lula/ngx-summernote#12]
Hi,

Initially i have tried cloning your repo with my git and found issue in pasting images after integrating with my application.

Then i created new fresh application by ng new <appName> and followed all your steps which was mentioned. 
Found the same issue, its not allowing pictures to be pasted through clipboard.

I am using Angular 7.0.6. Seems some additional steps we need to do in order to make it work. Its working better when i clone repo and use it as standalone because that time it uses inbuilt CLI.

The moment i integrate with higher version its not allowing pictures to be pasted.

Please let me know your suggestion and experience to resolve this. I would highly appreciate.

Thanks
Ramit

**Comment by ishan123456789** [comment]
Can you please provide a little bit of detailed description of the error you're getting, your angular core and `ngx-summernote` version. I'll see if I can help.

**Comment by lula** [comment]
@ramitmathur27m just created a fresh new project with Angular@7.1.0 and summernote@0.8.10 and I'm pasting images without problems. Are you sure you are using summernote@0.8.10? I actually encounter your problem with summernote@0.8.11 so I believe this issue can be reported there.

**Comment by ramitmathur27m** [comment]
So how can i install summernote@0.8.10 since i used  **npm install --save ngx-summernote summernote jquery**  for summernote installation.

can i use like n**pm install --save ngx-summernote summernote@0.8.10 jquery**  ??

**Comment by lula** [comment]
Yes. If you already installed ngx-summernote and jquery, you can just install summernote

`npm install --save summernote@0.8.10`

**Comment by ramitmathur27m** [comment]
Hi,

Sorry for late respond, you were right. it started working with summernote 0.8.10 version after degrading from 0.8.11,

Thanks
Ramit
