### ISSUE TITLE
Picture popup is not enabled for choose file

### ISSUE THREAD

**Issue by Praveensjk** [lula/ngx-summernote#123]
![ImageIssue](https://user-images.githubusercontent.com/5038406/118644189-2b88ec00-b7fb-11eb-8d7a-74aa26673cac.PNG)
I m not able to upload any image by choosing file or entering link. Popup is getting blurred after click in picture button.
I have attached screenshot for  reference.
 I m using angular 7 version for development.

Do let me know if you need any more info for troubleshoot. 
It will be great get the response earliest.

Thank you,
Praveen

**Comment by Praveensjk** [comment]
### ### ### j

**Comment by lula** [comment]
hello @Praveensjk is this a summernote problem, or is it related to this lib? Have you already tried to post it to summernote repository? Closing the issue for now, feel free to reopen it.
