### ISSUE TITLE
Tooltip cut 

### ISSUE THREAD

**Issue by rohit64Singh222** [lula/ngx-summernote#126]
Hello,

We using ngx-summernote ^0.7.8  getting issue of tooltip cut

![image](https://user-images.githubusercontent.com/57747188/120965743-e9602400-c782-11eb-8339-1337708a33fd.png)

It's issue generate when put as below code.

 ![image](https://user-images.githubusercontent.com/57747188/120966378-c2eeb880-c783-11eb-93d5-637623a184db.png)

And bootstrap have option for tooltip container body, tooltip html put inside main body..so same option provide in it if possible..

Suggest any solution.. if any other option exists..

**Comment by lula** [comment]
Hello @rohit64Singh222 is this a summernote problem or actually related to this lib? Have you already tried to post id in summernote repository? Closing the issue for now, feel free to reopen it.
