### ISSUE TITLE
Can we add authorization header when call uploadImagePath

### ISSUE THREAD

**Issue by isoftvn** [lula/ngx-summernote#130]
Can we add authorization header when call uploadImagePath

**Comment by lula** [comment]
Hello @isoftvn I just released 0.8.6. In summernote options you should have now `uploadImageRequestOptions`, which are basically the HttpClient post options:

`this.http.post(this._options.uploadImagePath, data, this._options.uploadImageRequestOptions)`

Please reopen the issue if you should have any problem
