### ISSUE TITLE
Can't bind to 'ngxSummernote' since it isn't a known property of 'div'

### ISSUE THREAD

**Issue by i-mahmud** [lula/ngx-summernote#134]
I followed all the instructions mention on https://github.com/lula/ngx-summernote,
still I got this error from the html file.

Can anyone please specify where I would need to check for this to resolve.

**Comment by Skywalker-72** [comment]
@lula I am using this module in 2 projects, say App1 and App2
Both are on Angular 10
App1 is a Universal application(server side rendered)
App2 is a conventional angular application

ngx-summernote works on App1 and not on App2.

Everytime I do a npm start, it gives me this error. Any insights?

**Comment by Skywalker-72** [comment]
Hey @i-mahmud , is there a chance that you have 2 modules in yorh project other than an app module and you are trying to import it in the second module?

**Comment by punisher-n** [comment]
I got the same error like @i-mahmud  mentioned  above 
"  I followed all the instructions mention on https://github.com/lula/ngx-summernote,
still I got this error from the html file.

Can anyone please specify where I would need to check for this to resolve."  

And i only have one Module
