### ISSUE TITLE
ETA on Angular v13 support?

### ISSUE THREAD

**Issue by alexaka1** [lula/ngx-summernote#136]
Using ngx-summernote in an Angular 13 project produces the following npm error:
```console
npm WARN Could not resolve dependency:
npm WARN peer @angular/common@"8.x - 12.x" from ngx-summernote@0.8.7
npm WARN node_modules/ngx-summernote
npm WARN   ngx-summernote@"^0.8.7" from the root project
```

Aside from npm having obvious issues with it, the lib seems to work with Angular 13 without any obvious problems.

**Comment by RogierVC** [comment]
+1

**Comment by ozcanavtat** [comment]
Could not use it with Angular v13. What is the v13 plan?

npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree._

**Comment by lula** [comment]
Hello everyone, I've release 0.8.8 with support for Angular 13.

**Comment by RogierVC** [comment]
That's great! Thank you for this.
I would advise to also update the read me so it's clear which version supports Angular 13

**Comment by lula** [comment]
Hello @RogierVC thanks! Readme updated 🎉
