### ISSUE TITLE
2 way binding not working or how do I get the inner Html 

### ISSUE THREAD

**Issue by bd-at-vp** [lula/ngx-summernote#15]
I have the editor loaded and the initial content loaded using the summernoteModel:

In component ts:
`private wysiwygContent: string;`
`this.wysiwygContent = '<p>Testing....</p>';`

In template:
`<div [ngxSummernote]="wysiwygConfig" [summernoteModel]="wysiwygContent"></div>`
testing 2 way binding:
`<div>{{wysiwygContent}}</div>`

However as the content is edited there is no 2 way binding between the summernoteModel and my property wysiwygContent. Is this supported and if so how?
If not how do I get the updated content and manually update the property wysiwygContent,  preferably without using jQuery and accessing summernote directly.

I am using the config:
`this.wysiwygConfig = {
      toolbar: [
        ['style', ['bold', 'italic', 'underline', 'clear']],
        ['font', ['bold', 'italic', 'underline', 'strikethrough', 'superscript', 'subscript', 'clear']],
        ['fontsize', ['fontname', 'fontsize', 'color']],
        ['para', ['style0', 'ul', 'ol', 'paragraph', 'height']],
        ['insert', ['table', 'link', 'hr']],
        ['misc', ['undo', 'redo', 'codeview']]
    ]
    };`

Thanks.

**Comment by lula** [comment]
Hello @bd-at-vp just add the two-way binding and it should work:

```
<div [(summernoteModel)]="wysiwygContent" [ngxSummernote]="wysiwygConfig"></div>
```

**Comment by mayilsaran** [comment]
i am also using summernote.
Pls  add this page details shortly , in your main github(Read Me)  **https://github.com/lula/ngx-summernote**
