### ISSUE TITLE
Angular 14 support

### ISSUE THREAD

**Issue by shubhamseth29** [lula/ngx-summernote#158]
I am trying to use ngx-summernote in my Angular 14 application and I found it that it supports till Angular 12 (or maybe 13 as per some PR I saw).

Can you please upgrade it for angular 14 support or tell by when can it happen :)

**Comment by RogierVC** [comment]
In the meantime, Angular 15 came out, so I think it's best to make this package compatible for Angular 15 straight away. :)

**Comment by jonasduever** [comment]
For me, it works without any issues. 👍
I'm not using all of the features though, but I think making it compatible with Angular 15 would not require a lot of work.

Since Angular 14, I'm using a `package.json` `overrides` item to make it "compatible":
```
    "ngx-summernote": {
      "@angular/common": "$@angular/common",
      "@angular/core": "$@angular/core",
      "@angular/forms": "$@angular/forms"
    }
```

**Comment by andreyjkee** [comment]
Got Ivy related warning during the build on Angular v15:

> Processing legacy "View Engine" libraries:
> - ngx-summernote [es2015/esm2015] (https://github.com/lula/ngx-summernote.git)
> Encourage the library authors to publish an Ivy distribution.

**Comment by lula** [comment]
hi all, please see 0.8.9 with angular 14 support.

**Comment by RogierVC** [comment]
OK thanks, but what about Angular 15? Also, the version does not appear on GitHub as a release.

**Comment by lula** [comment]
If it's "just" a matter of Ivy related warnings (which to be honest i believe also happen in angular 14) I can add the version. To be Ivy compliant, though, would require time that unfortunately i don't have right now

**Comment by lula** [comment]
0.9.0 for angular 15

**Comment by RogierVC** [comment]
You are awesome!

In my case, updating my whole Angular project was blocked due the following error, which should now be resolved:
`Package "ngx-summernote" has an incompatible peer dependency to "@angular/core" (requires "8.x - 13.x" (extended), would install "15.1.0").`
