### ISSUE TITLE
How to add a code block button in toolbar;?

### ISSUE THREAD

**Issue by ishan123456789** [lula/ngx-summernote#21]
I want something like [this](https://github.com/summernote/summernote/issues/1945) can I use this with ngx-summernote

**Comment by lula** [comment]
Hello @ishan123456789, I'm afraid this is not supported yet.

**Comment by ishan123456789** [comment]
I'm working on it will generate a PR for it this month

**Comment by lula** [comment]
Thank you Ishan!!! I worked on it as well: could you please check branch issue-#21? See example app with custom button.

**Comment by ishan123456789** [comment]
I'll clone your branch and will put my work in  it. I've done a little enchantment which will make it better

**Comment by lula** [comment]
Great! What have you done?

**Comment by ishan123456789** [comment]
Created a PR for it https://github.com/lula/ngx-summernote/pull/23 please review 
Added option to add code block to selected text like wrapping the selected text into our code block
Please let me know if any improvement needed I'll work by the next weekend

**Comment by lula** [comment]
@ishan123456789 sorry for delay!! I released a new version with code block button based on your PR. I made some mess so I actually closed your PR and create a new one where I also added the possibility to add custom buttons in the app. Please check and see if that's ok with you! Thanks!

**Comment by ishan123456789** [comment]
Must be something very good thanks for your time on the plugin it's quite good and thealternates are paid and quite expensive. So I wish to make it a complete package. Thanks @lula

**Comment by lula** [comment]
Thanks to you @ishan123456789 !!!!!
