### ISSUE TITLE
Undo removes initial text 

### ISSUE THREAD

**Issue by Dertcmak** [lula/ngx-summernote#22]
Buttton undo removes initial text. 

My .html file: 
```
<div [formGroup]="fg">
  <div formControlName='editorText' [ngxSummernote]="configEditor"></div>
</div>
```
My .ts file:
```
...
editorControl: FormControl = new FormControl('test');

  constructor(fb: FormBuilder) {
    this.fg = fb.group({
      editorText: this.editorControl
    });
  }

  configEditor = {
    tabsize: 2,
    height: 600,
    toolbar: [
      ['misc', ['undo', 'redo']],
      ['font', ['bold', 'italic', 'underline', 'strikethrough', 'clear']],
      ['para', ['style0', 'ul', 'ol', 'paragraph']]
    ],
  };
...
```

Is there a way how to solve that ?

**Comment by lula** [comment]
Hello @Dertcmak what do you mean with initial text? Undo button undo the last text you typed.

**Comment by Dertcmak** [comment]
Hi @lula, what I mean is when I click on undo button for the first time then the text that I have in my FormControl ( in my case 'test')  gets removed.

**Comment by Dertcmak** [comment]
I have created a repository where you can check it [repo](https://github.com/Dertcmak/ngx-summernote-test/tree/master/ngx-summernote)

**Comment by lula** [comment]
Hi @Dertcmak thanks.

See [here](https://github.com/summernote/summernote/issues/2595).

Setting the initial model from the FormControl triggers the model update, so undo reset the model to initial state (empty).

What you should do is to set the initial text directly in HTML, something like: 

```
<div [formGroup]="form">
  <div formControlName="html" 
       [ngxSummernote]="config"
       [ngxSummernoteDisabled]="editorDisabled"
       (blur)="onBlur()">
  initial
   </div>
</div>
```

In this case undo will reset to 'initial'.

**Comment by Dertcmak** [comment]
Thanks for your answer. 
I've decided to use [(summernoteModel)] instead.
