### ISSUE TITLE
Drag & drop

### ISSUE THREAD

**Issue by salmanali2074** [lula/ngx-summernote#24]
Hi, 
I am dropping a select text (such as a word) in the middle of the content but it always drops and appears at the start position. 

Please see attached picture.  I was selecting and dragging the word 'Manager' in the box **[ ]** but once I drop it, it always appears at the start of the content. 

Please let me know if there is a way to drag drop (a word or text) at a specific location in the content.  

Thanks 

![summernote-sali](https://user-images.githubusercontent.com/7494660/54542604-189fd600-496a-11e9-9835-10643b4ce02c.PNG)

**Comment by lula** [comment]
@salmanali2074 from what I can see it dragged text gets appended. Anyway, I don't think that this is possible here, as it's summernote who handles drag and drop. You may try to get some help there I guess.
