### ISSUE TITLE
Disable/ReadOnly ngxSummernote in Angular 7

### ISSUE THREAD

**Issue by ramitmathur27m** [lula/ngx-summernote#25]
Hi,

I am trying to disable ngxSummernote which i am using under Angular 7  but somehow its not disabling the content inside summer note.

code:-
**<input [disabled]="role=='R'" name ="modelContainerLabels"  [ngxSummernote]="config" [(ngModel)]="labelingReviewInfo.modelContainerLabels">**

i am trying [disabled]="role=='R'"

This is not working, do we have any other alternative??

Thanks
Ramit

**Comment by lula** [comment]
@ramitmathur27m ngx-summernote provide an input you can use to disable the whole editor:

```
<div formControlName="html" 
       [ngxSummernote]="config"
       [ngxSummernoteDisabled]="editorDisabled"
       (blur)="onBlur()">
 </div>
```

Secondly I don't think you should use any `input` to use ngx-summernote, a `div` is enough.
