### ISSUE TITLE
styling and full screen issue with Angular material.

### ISSUE THREAD

**Issue by Naveed1842** [lula/ngx-summernote#26]
I'm able to run ngx-summernote but the problem is that,I'm using angular-material.The editor ngx-editor **show button large**.One other problem is that I'm **not able** to view the editor in full screen.
![SellTime   CMS   E Commerce Web Portal](https://user-images.githubusercontent.com/22956528/54870215-4d29ec80-4dc5-11e9-89f5-d18c7bd43e81.png)

**Comment by lula** [comment]
@Naveed1842 I can't reproduce it. I added the fullscreen button and when I press it the editor get fullscreen (relative to the browser window). Please share a test repo or some plunkr if possible.

**Comment by KK220794** [comment]
Even I faced the same issue. On integrating with angular material, the buttons are getting large. Is there any other way by which i can integrate angular icons ?
