### ISSUE TITLE
Can you add LICENSE file?

### ISSUE THREAD

**Issue by ktanakaj** [lula/ngx-summernote#29]
Hi! I'm finding a rich text editor for my Angular project.
I want to use your library.
But there are no licenses. I can use only OSS libraries.

Can you add following license information and rerelease the library?

* `LICENSE.txt` file (https://help.github.com/articles/licensing-a-repository/)
* License section in `README.md`
* `license` field in `package.json` (https://docs.npmjs.com/files/package.json#license)

**Comment by lula** [comment]
Hello @ktanakaj please check latest version 0.6.4. It should have a LICENSE file and package.json should be also changed accordingly. Please let me know if it's ok now. Thanks!

**Comment by ktanakaj** [comment]
I got latest version with LICENSE file and new package.json now :thumbsup:
Thank you very much for your quick response!

**Comment by lula** [comment]
Great! Issue closed.
