### ISSUE TITLE
Allow editor to be disabled via [disabled] propery

### ISSUE THREAD

**Issue by mungpara** [lula/ngx-summernote#3]

**Comment by lula** [comment]
Hello! Feature added in new release 0.5.5.

Use ngxSummernoteDisabled to enable/disable the editor. See demo app in repo as an example.

**Comment by mungpara** [comment]
allow disabled using [disabled] instead of ngxSummernoteDisabled

**Comment by llulani** [comment]
[disabled] property is also used by Angular components and directives and you might encounter warnings, errors, etc (e.g. with reactive forms).

**Comment by lula** [comment]
[disabled] property is also used by Angular components and directives and you might encounter warnings, errors, etc (e.g. with reactive forms).
