### ISSUE TITLE
Editor not initialized when initializing listeners, if immediateAngularModelUpdate = true option is used

### ISSUE THREAD

**Issue by bogdandynamic** [lula/ngx-summernote#31]
The problem occures when using `immediateAngularModelUpdate = true` in initialization array. While debugging, I found out that you are trying to bind keyup event on _editor, which at this time is not initialized:
https://github.com/lula/ngx-summernote/blob/c86b1b7eda94f42dc03179134d28b18a7c79640f/projects/ngx-summernote/src/lib/ngx-summernote.directive.ts#L217-L223

To fix this issue, please inverse the following lines (`this.zone.runOutsideAngular` with  `this.initListeners`):

https://github.com/lula/ngx-summernote/blob/c86b1b7eda94f42dc03179134d28b18a7c79640f/projects/ngx-summernote/src/lib/ngx-summernote.directive.ts#L233-L242

**Comment by lula** [comment]
Hello @bogdandynamic it should be fixed in 0.6.5. Please let me know. Cheers!
