### ISSUE TITLE
Editor not working (Nothing is shown)

### ISSUE THREAD

**Issue by lidibe** [lula/ngx-summernote#32]
Team,

I am trying an integration of summernote using Angular 7. Despite the fact that there is no error in the console, the editor is not displayed.

app.module.ts

`....
import { NgxSummernoteModule} from "ngx-summernote";
...

@NgModule({
  imports: [
    ...
    NgxSummernoteModule,
  ],
  ...
})
`

app.component.html
` <div [ngxSummernote]></div>`

Did I miss anything?

Thanks.

L

**Comment by lula** [comment]
Hello @lidibe have added all scripts and css in angular.json?

**Comment by 72mahdii** [comment]
### You must insert these code lines into angular.json file:

![help](https://user-images.githubusercontent.com/47686564/56884031-be705580-6a7d-11e9-8bd5-d11231087673.png)
