### ISSUE TITLE
I want to insert text at cursor point inside summernote area . Using outside button click. It is possible??

### ISSUE THREAD

**Issue by bmadhan90** [lula/ngx-summernote#33]
Refer below image.

![image](https://user-images.githubusercontent.com/37164224/56339663-c1e42100-61e1-11e9-8277-a1bb91f0970c.png)

**Comment by lula** [comment]
Hello @bmadhan90 can [this](https://github.com/summernote/summernote/issues/282#issuecomment-45093423) help?

**Comment by Rae-Lin** [comment]
Hi @bmadhan90 

I am also looking for this issue, did you find any solution?

Thanks.
