### ISSUE TITLE
get code

### ISSUE THREAD

**Issue by ViniciusFernando** [lula/ngx-summernote#34]
I need to get the html code from the editor, but the code is breaking some special characters like for example "á" or "õ".

<textarea id="summernote-textarea" [ngxSummernote] [(summernoteModel)]="template"></textarea>

**Comment by lula** [comment]
Hello @ViniciusFernando I can't reproduce it:

<img width="172" alt="Screenshot 2019-04-25 at 14 52 30" src="https://user-images.githubusercontent.com/614544/56737044-d720f880-6769-11e9-9408-115b1ea5935d.png">

Perhaps can you share a test repo or plunkr?
