### ISSUE TITLE
Upload Image To .Net Core API

### ISSUE THREAD

**Issue by 72mahdii** [lula/ngx-summernote#35]
### I want to store image uploaded from summernote into a .net core api, but I get this error

![er](https://user-images.githubusercontent.com/47686564/56882184-21f78480-6a78-11e9-8a7f-f9409b228f3a.jpg)

### Component and summernote config:

![config](https://user-images.githubusercontent.com/47686564/56882167-1310d200-6a78-11e9-836f-0af215ff2034.png)

### Html Code:

![summernote](https://user-images.githubusercontent.com/47686564/56882310-7b5fb380-6a78-11e9-9eeb-c594e1cf0deb.jpg)

### .net core Api action

![api](https://user-images.githubusercontent.com/47686564/56882446-d5f90f80-6a78-11e9-8e2c-0244ec81d866.jpg)

**Comment by lula** [comment]
Hello @72mahdii I don't understand. You are uploading to a http://localhost:5050/.../TextEditorImage: is that working? Can you see the uploaded file in server directory? What is the http://localhost:5050/ck_img/....???

**Comment by 72mahdii** [comment]
**Thanks for your answer@lula** 
Yes, the upload process on http://localhost:5050/.../TextEditorImage is successfully, and uploaded file show up in server directory.

http://localhost:5050/ck_img/... is address of uploaded file on server.

The problem is that when return this address to Summernote, it says 'Not Found', but the file uploaded successfully and address is correct.

**The whole idea is ,upload image on Summernote and  send file to .Net Core Api   to add it to server, and return its address to Summernote, every things are fine on the server with uploaded file, and the adress is also correct, but it says Not Found...!**
