### ISSUE TITLE
italics in the editor not working

### ISSUE THREAD

**Issue by KK220794** [lula/ngx-summernote#37]
![image](https://user-images.githubusercontent.com/46670285/58245486-86a1b880-7d72-11e9-94db-39f14725e6ec.png)

it gives some random texts when italics is fired

**Comment by lula** [comment]
Not reproducible:

<img width="449" alt="Screenshot 2019-12-18 at 11 16 57" src="https://user-images.githubusercontent.com/614544/71077548-ebe24e80-2187-11ea-99b4-fac88ab47273.png">
