### ISSUE TITLE
TS2339: Property 'summernote' does not exist on type 'JQueryStatic'.

### ISSUE THREAD

**Issue by lilworks** [lula/ngx-summernote#4]
I'm trying to create a custom button.
I use the summernote exemple
```
var HelloButton = function (context) {
      var ui = $.summernote.ui;

      // create button
      var button = ui.button({
        contents: '<i class="fa fa-child"/> Hello',
        tooltip: 'hello',
        click: function () {
          // invoke insertText method with 'hello' on editor module.
          context.invoke('editor.insertText', 'hello');
        }
      });

      return button.render();   // return button as jquery object
    }
```
But I have got this error
TS2339: Property 'summernote' does not exist on type 'JQueryStatic'.

**Comment by sevaru** [comment]
It seems like summernote doesn't have proper types for typescript.

But you have a couple of options here e.g.
1) cheaty as any
```
var ui = ($ as any).summernote.ui;
```

2) extend JQueryStatic
``` //in a separate file like types.d.ts
interface JQueryStatic {
   summernote: {
      ui: any; // or some more reasonable type
   }
}
```

**Comment by lula** [comment]
@lilworks does @sevaru answer fulfill your need?

**Comment by damiencuvillier** [comment]
On angular 8, cheat with any was indeed working. 

It's not the case with angular 11
@sevaru I do not understand easily the other way with extending JqueryStatic

**Comment by sevaru** [comment]
As far as I know "as any" works in any typescript/angular setup
Can you please provide some errors.

As for extending jquery interface
Just create some file in src directory name it something like types.d.ts
and paste that code into it
```
```
