### ISSUE TITLE
XSS - Cross Site Scripting, is it an issue?

### ISSUE THREAD

**Issue by EvanSevy** [lula/ngx-summernote#41]
Do I need to worry about XSS when using ngx-summernote?  If so, what might be the best way to handle it?  I'm new to the issue and would appreciate your thoughts.  Thanks.

**Comment by EvanSevy** [comment]
Here is a resolution to my question.  It looks like Angular automatically sanitizes html content.

Straight from Angular.io (https://angular.io/guide/security):

> When a value is inserted into the DOM from a template, via property, attribute, style, class binding, or interpolation, Angular sanitizes and escapes untrusted values.

Here's a rule of thumb when dealing with storing html in a db:  https://stackoverflow.com/a/21662837/230128

**Comment by lula** [comment]
Hello @EvanSevy sorry for delay I'm super busy at work in these period. To answer to your question, yes Angular provides sanitizing mechanisms that you can use in your app. For now you can do that to ensure xss security. When I have some spare time I'll try to include something in this lib as well.

**Comment by lula** [comment]
@EvanSevy if you're still having thoughts about it, see [XSS protection for CodeView](https://summernote.org/deep-dive/#xss-protection-for-codeview). You can prevent in summernote xss attacks by filtering in code view. You can add additional filters, as shown [here](https://github.com/lula/ngx-summernote/blob/d6242efa48ac68adb02f25918b55f626b5861bc0/src/app/app.component.ts#L35) for onmouseover attribute.
