### ISSUE TITLE
Use summernote() function

### ISSUE THREAD

**Issue by DydjyZ** [lula/ngx-summernote#42]
Hello,

i want to use the summernote() function to reset my textarea :

$('#summernote').summernote('reset');

I've tried with ViewChild, does not work, same for jQuery manner..

Do you know how to do this ?

Thanks you,
Dylan

**Comment by lula** [comment]
Hello @DydjyZ 

```
 <div formControlName="html" id="summernote"
       [ngxSummernote]="config"
       [ngxSummernoteDisabled]="editorDisabled"
       (blur)="onBlur()">
   </div>
```
Then `$('#summernote').summernote('reset');` should work.

Cheers

Luca
