### ISSUE TITLE
Double caret icons on the dropdown menu

### ISSUE THREAD

**Issue by JanGruber** [lula/ngx-summernote#43]
Dear Team,

I've integrated summernote in my website using Angular 7 but at the dropdown menus in the toolbar two caret icons are showing.

![dropdown](https://user-images.githubusercontent.com/32123771/60667093-efe41380-9e68-11e9-8b64-a87f5ee5c218.PNG)

Any ideas? Thanks.

**Comment by lula** [comment]
Hello @JanGruber 

Well that's strange... What config did you use?

Cheers

Luca

**Comment by jowCode** [comment]
Hi there. Same problem here.
angular 7.2
ngx-summernote 0.6.5
ngx-bootstrap 5.50
bootstrap 4
I am using "node_modules/summernote/dist/summernote-lite.min.css" in angular.json. Could that be the reason?

**Comment by lula** [comment]
Hello @jowCode as you're using bootstrap I guess you should probably use an other css (like `summernote-bs4.min.css`)  and possibly also add the corresponding js script (like `summernote-bs4.min.js`). See in `node_module/summernote/dist` the available css and js.

**Comment by Must57** [comment]
Hello I have the same issue but anything resolve it

**Comment by brijesh1ec** [comment]
i have same issue ,  "ngx-summernote": "^0.9.0",
"@ng-bootstrap/ng-bootstrap": "^14.0.1",

"summernote": "^0.8.20",
"bootstrap": "^5.2.3",

**Comment by mt300** [comment]
Same issue here, bootstrap 5.2, but no VUE project, I'm using apache2 and PHP, with HTML/CSS/JS frontend
