### ISSUE TITLE
Is there any ways or callback functionality for deleting an uploaded images in the server?

### ISSUE THREAD

**Issue by louislingatong** [lula/ngx-summernote#44]
Hi team,

I used the `uploadImagePath` option in config to store the uploaded images to the server.

And my concern here is that if I want to cancel or delete the images I added, is there any way to remove the images stored in the server?

**Comment by lula** [comment]
Hello @louislingatong 

there's no way so far. You can create a custom button or your own differente logic outside summernote.

Cheers

Luca
