### ISSUE TITLE
On Init Mark dirty on true

### ISSUE THREAD

**Issue by Montellanos** [lula/ngx-summernote#45]
On start the binding the form control has marked dirty on true.

`<div [ngxSummernote]="summerNoteConfig" [formControl]="inputControl"></div>`

And the validations are displayed.

The dirty atribute only be mark on start use the component.

Chears..

**Comment by lula** [comment]
Hello @Montellanos 

I don't understand what is the issue. On init the form is not dirty, as it should be.

Cheers,

Luca
