### ISSUE TITLE
how can i get the value from the component?

### ISSUE THREAD

**Issue by grijalvaromero** [lula/ngx-summernote#46]
I can't get the value, in angular form the code is:

`this.myForm.value.name`

I try this:
` <div  [ngxSummernoteView]="content"  #summer formControlName="sumer" ></div>`

With angular forms:
`this.myForm.value.name`

With ViewChild
`this.summer.nativeElement.value`

also with innerHTML

but for the summernote component what is the way?

thanks

**Comment by lula** [comment]
Hello @grijalvaromero 

if you use reactive forms you have to use the form. In your case:

````
<div [ngxSummernoteView]="content" #summer formControlName="sumer"></div>

this.form.sumer.value
```

Cheers

Luca
