### ISSUE TITLE
Insert image popup is broken

### ISSUE THREAD

**Issue by eladco898** [lula/ngx-summernote#48]
![insertImage](https://user-images.githubusercontent.com/40334143/62953614-860b4200-bdf6-11e9-8e57-70174777485f.PNG)

**Comment by eladco898** [comment]
Any update here?

**Comment by lula** [comment]
@eladco898  what version of summernote were you using? What browser are you using? Everything seems just fine to me. Sorry for delay, but I had terrible months at works and home. I had no time to even reply earlier.

**Comment by eladco898** [comment]
Maybe I had a mixed versions of angular and your module.
Looks OK now.
Thanks
