### ISSUE TITLE
UI bugs in module

### ISSUE THREAD

**Issue by eladco898** [lula/ngx-summernote#49]
The following features are not working:

- Color selection - Reset to default

- 'Bold','Italic','Underline' in the toolbar doesn't appear to be enabled after the user clicked on them

**Comment by lula** [comment]
@eladco898 it seems to work jsut fine to me when i click on remove font style

<img width="209" alt="Screenshot 2019-12-18 at 13 04 36" src="https://user-images.githubusercontent.com/614544/71085085-f821d800-2196-11ea-9f86-8d3ed66181d6.png">

**Comment by eladco898** [comment]
I meant to click on this:
![summer](https://user-images.githubusercontent.com/40334143/71367052-7e318a80-25ac-11ea-94cd-ed04e391c4e8.PNG)

**Comment by lula** [comment]
> Elad Cohen <notifications@github.com>
> I meant to click on this:
> ![D2BF13CE-7A49-4CFC-B7F1-1F1A17EE3C2F](https://user-images.githubusercontent.com/614544/71584598-8c832780-2b13-11ea-8286-719f9be1eef2.png)

I don't see any problem with it, with summernote@0.8.10. What summernote version are you using?

**Comment by eladco898** [comment]
I got unmatched versions with my Angular.
Everything works great now.
Thanks
