### ISSUE TITLE
Invoke summernote function 

### ISSUE THREAD

**Issue by kamlesh0606** [lula/ngx-summernote#5]
Hi,

I need to invoke summernote function Like $('#summernote').summernote('editor.insertText', 'This text should appear at the cursor');  

any option for this ?

I need to insert text at current cursor position , so 
 Ref. Link -  https://github.com/summernote/summernote/issues/282

Thanks
kamlesh

**Comment by lula** [comment]
Hello @kamlesh0606 ! Sorry for delay. You can use angular forms for this, like:

`this.form.get('html').setValue("hello!")`

**Comment by kamlesh0606** [comment]
Hello,

`this.form.get('html').setValue("hello!")` use for set value but i need to insert text at **cursor position**  

have any way for this.

Thanks

**Comment by Rae-Lin** [comment]
Hi @kamlesh0606,

I am also looking for this issue, did you find any solution?

Thanks.

**Comment by kamlesh0606** [comment]
Hi @Rae-Lin , No

**Comment by JudgementHC** [comment]
Greetings, @Rae-Lin @kamlesh0606 
Has a solution been found?
