### ISSUE TITLE
İmage Upload With Header(image upload with jwt bearer token)

### ISSUE THREAD

**Issue by codehope-AtCompany** [lula/ngx-summernote#52]
Im using jwt-bearer auth on my project that using asp.net core Rest Api and Angular .Instead of using base64 images,i want to upload images to my own server  .But i need to send image with header that contains token information.I tried to use uploadImagePath but it gives 401 Unauthorized.Is there a way to upload image with header ?

**Comment by lula** [comment]
@codehope-AtCompany have you tried with an Angular interceptor?
