### ISSUE TITLE
Uploade and show image in Angular 8??

### ISSUE THREAD

**Issue by amannguptaggg** [lula/ngx-summernote#53]
I'm using summernote editor in my angular 8 project. Its working fine.
But Images are uploading and showing in base64.

How can i use upload image and use nxgSummernoteView innerHTML to show images in content.
Contents are blog post.

Please help..

**Comment by Sarthaktydy** [comment]
Found anything?

**Comment by arunj-nd** [comment]
Any update??

**Comment by lula** [comment]
Not sure this is an issue. If you want to upload an image to a server in a different format just convert it.
