### ISSUE TITLE
How to add authentication header with URL mapped to save image ?

### ISSUE THREAD

**Issue by swapnil-townscript** [lula/ngx-summernote#54]

**Comment by monzir-dev** [comment]
I have the same question. how do I attach the auth token header when image upload post request is made on the uploadImagePath?

![image](https://user-images.githubusercontent.com/8929804/115829955-6f254b80-a431-11eb-98ac-6c3432cd5b11.png)

**Comment by monzir-dev** [comment]
FYI I got it working using a authinterceptor using HttpInterceptor
