### ISSUE TITLE
Insert Image Button positioned weird

### ISSUE THREAD

**Issue by SilinaGeorge** [lula/ngx-summernote#56]
![summernote-insert-image](https://user-images.githubusercontent.com/19698115/64495764-507a3d00-d26c-11e9-9823-d1303257e17e.PNG)

I want the button to be placed in the center.

this is my html markup
```<textarea id="note" [ngxSummernote]='editorConfig' [(ngModel)]="content"></textarea>```

I'm using Angular 8

**Comment by lula** [comment]
@SilinaGeorge guess you can remove float on button with css.

<img width="131" alt="Screenshot 2019-12-18 at 12 59 09" src="https://user-images.githubusercontent.com/614544/71084743-3ec30280-2196-11ea-93c7-ed8c2547c21f.png">
