### ISSUE TITLE
blur run a lot of time

### ISSUE THREAD

**Issue by guypeled1** [lula/ngx-summernote#59]
Hi,
i have an a form that there is a 4 fields in the component that are creating dynamiclly.
this is how i pass the code:
`
this.formText.forEach(element => {
 let _$element: any = (<any>$(element.nativeElement));
          _$element.summernote('code', this.answars[counter]);
})
`
when i'm adding blur to the elemnets:
`
 _$element.on('summernote.blur', () => {

})
`

for some reason it runs 17 times.
why this is happening and how can i solve this?

**Comment by lula** [comment]
@guypeled1 please share a plunkr, or stackblitz or other to reproduce the issue. Thanks

**Comment by lula** [comment]
Anyway, from what I can see, normally blur runs once, when you blur event is triggered by summernote. If it runs multiple times than it can't be related to this lib.
