### ISSUE TITLE
Is there a method to send image to server instead of creating a base64 image

### ISSUE THREAD

**Issue by ishan123456789** [lula/ngx-summernote#6]
Here's an implementation in `jQuery` https://gist.github.com/tojibon/118b4c80f328ca394c751d218f330a19
is there a method to implement it using your plugin?
Please, let me know if this feature is available

**Comment by hitpopdimestop** [comment]
I have the same question

**Comment by ishan123456789** [comment]
I'll generate a pull request soon most probably by the end of this week. @hitpopdimestop

**Comment by lula** [comment]
Hello guys, sorry for delay! I still had no time to test it myself, but from what I can see it might be enough to add the function in you config. Have you already tried something like that? 

```
Component js:
myConf = {
onImageUpload: () => {...}
}

Component html:
<div [ngxSummernote]="myConf"></div>
```

**Comment by ishan123456789** [comment]
Hi @hitpopdimestop  @lula I've generated the above PR.
@hitpopdimestop  you can clone my project and work accordingly or let me know I can create a package of my own if needed till PR is accepted.

**Comment by hitpopdimestop** [comment]
@ishan123456789 many thanks! That is what I really needed. I'll wait until it is accepted, for now, no hurry here. Thanks again!

**Comment by lula** [comment]
@hitpopdimestop please check [this comment](https://github.com/lula/ngx-summernote/pull/10#issuecomment-447660955), especially point 2, and share your thoughts if you would.

**Comment by lula** [comment]
Closing! See [this comment](https://github.com/lula/ngx-summernote/pull/10#issuecomment-448371002) for more info.
