### ISSUE TITLE
How set language in summernote config?

### ISSUE THREAD

**Issue by gianlucamachado** [lula/ngx-summernote#60]
Any solution to translate ngx-summernote component?

**Comment by nhilaire** [comment]
just founded, add lang to your config object 

`    config: any = {
        height: "calc(100vh - 340px)",
        toolbar: [
            ["misc", ["codeview", "undo", "redo"]],
            ["font", ["bold", "italic", "underline", "strikethrough", "superscript", "subscript", "clear"]],
            ["fontsize", ["fontname", "fontsize", "color"]],
            ["para", ["style0", "ul", "ol", "paragraph", "height"]],
            ["insert", ["table", "picture", "link", "video", "hr"]]
        ],
        lang:"fr-FR"
    };`

and add correct language to your scripts in angular.json 

`            "scripts": [ 
              "node_modules/jquery/dist/jquery.min.js",
              "node_modules/summernote/dist/summernote-lite.js",
              "node_modules/summernote/lang/summernote-fr-FR.js"
            ],`
