### ISSUE TITLE
Incompatible with Angular 9

### ISSUE THREAD

**Issue by Barzille** [lula/ngx-summernote#62]
With the current version of Angular 9 RC2  I am getting the following error:

    ERROR in ../node_modules/ngx-summernote/lib/ngx-summernote-view.directive.d.ts:1:22 - error TS2724: Module '"../../@angular/core/core"' has no exported member 'Renderer'. Did you mean 'Renderer2'?

    1 import { ElementRef, Renderer, AfterViewInit } from '@angular/core';
                       ~~~~~~~~

     ../node_modules/@angular/core/core.d.ts:5555:31
    5555 export declare abstract class Renderer2 {
                                       ~~~~~~~~~
    'Renderer2' is declared here.

**Comment by lula** [comment]
@Barzille haven't tried Angular 9 yet. Keep this issue open until Angular 9 is supported.

**Comment by jmannau** [comment]
I have migrated from Renderer to Renderer2 and opened a pull request. This should allow Angular 9 support.

**Comment by llulani** [comment]
@jmannau thank you! I'll have a look  during my holidays.

**Comment by kamlesh0606** [comment]
I also wait for this update.

**Comment by lula** [comment]
Hello guys, pull request have been merged and published to 0.7.1.

Cheers!

**Comment by hvaishnav** [comment]
Hello guys , 
  getting this error at this date too.
Does the problem is not resolved yet?

**Comment by lula** [comment]
Hello @hvaishnav as far as I can see it is. Do you still have a problem with Renderer2?

**Comment by NidheeshMv** [comment]
Hey Team,
Im using Nativescript version 8.2.1 supporting only Renderer. I want to migrate to Angular 9.
getting below issue

node_modules/@nativescript/angular/router/ns-router-link-active.d.ts:1:73 - error TS2724: Module '"../../../@angular/core/core"' has no exported member 'Renderer'. Did you mean 'Renderer2'?

1 import { AfterContentInit, ElementRef, OnChanges, OnDestroy, QueryList, Renderer } from "@angular/core";
~~~~~~~~

node_modules/@angular/core/core.d.ts:5752:31
5752 export declare abstract class Renderer2 {
~~~~~~~~~
'Renderer2' is declared here.

**Comment by lula** [comment]
`Renderer` is not supported anymore in Angular 9. BTW why are you asking this question here and not in Nativescript?

**Comment by dm-bishnoi** [comment]
Install  ngx-summernote
