### ISSUE TITLE
Not showing table selector in airMode

### ISSUE THREAD

**Issue by Sarthaktydy** [lula/ngx-summernote#63]
Steps to reproduce:-
1) Write airMode:true 
2) Click on table icon
3) gives blank bar (Column row selector not showing)

**Comment by lula** [comment]
@Sarthaktydy I see.  I need to check into this later.

**Comment by Sarthaktydy** [comment]
I added some CSS (Also using image for highlight and unhighlight) add this to your css and it'll work fine
`::ng-deep .note-dimension-picker {
  font-size: 18px;
}
::ng-deep  .note-dimension-picker-mousecatcher {
  position: absolute!important;
  z-index: 3;
  width: 10em;
  height: 10em;
  cursor: pointer;
}
::ng-deep  .note-dimension-picker {
  font-size: 18px;
}

::ng-deep .note-dimension-picker-highlighted {
  position: absolute!important;
  z-index: 2;
  width: 1em;
  height: 1em;
  background: url('../../../assets/summernoteTable/table_select.png') repeat;
}


::ng-deep .note-dimension-picker-unhighlighted {
  position: relative!important;
  z-index: 1;
  width: 5em;
  height: 5em;
  background: url('../../../assets/summernoteTable/table_not_select.png') repeat;
}`

**Comment by lula** [comment]
I tested with 0.8.15 and I can see the table buttons correctly. However, summernote seems to have a bug on air mode (see [issue 3588](https://github.com/summernote/summernote/issues/3588) in summernote.  I'm closing this, in favour of [75](https://github.com/lula/ngx-summernote/issues/75)
