### ISSUE TITLE
Add custom button

### ISSUE THREAD

**Issue by selmi5** [lula/ngx-summernote#66]
I followed the ngx-summernote documentation to add a custom button.
But when I click on this button I got this error:
Uncaught TypeError: Cannot read property 'invoke' of undefined.
It doesn't recognize the context.

**Comment by lula** [comment]
@selmi5 what version of summernote are you using? Everything works with 0.8.10 but not with further versions, it seems. See [here](https://github.com/summernote/summernote/issues/3249)
