### ISSUE TITLE
Problem with "Drag-and-drop" pasting a picture in google chrome

### ISSUE THREAD

**Issue by soullessuser** [lula/ngx-summernote#67]
Hi!
I have a problem with "Drag-and-drop" pasting a picture into the editor window. The problem occurs in google chrome (ver. 71.0.3578.98). The browser downloads and displays the picture, but does not paste it into the editor window.

Found something similar here:
https://github.com/summernote/summernote/issues/3067
https://github.com/summernote/summernote/pull/3068

**Comment by lula** [comment]
@soullessuser is this working correctly with summernote without this lib? This sounds to me more a summernote issue.

**Comment by lula** [comment]
Sorry I hadn't check your links. Indeed it seems related to summernote.

**Comment by lula** [comment]
Closing for now, feel free to reopen it in case everything works with summernote alone and not working with this lib.
