### ISSUE TITLE
Tooltips won't go away

### ISSUE THREAD

**Issue by w053lxl** [lula/ngx-summernote#68]
Picture kind of speaks for itself -- Got everything working - when I hover over a tooltip and move my mouse off, they other build up in the bottom left corner or don't go away.

Thanks,

![image](https://user-images.githubusercontent.com/33560756/71032387-42e21800-20e3-11ea-89cb-42090ef94979.png)

**Comment by w053lxl** [comment]
Found that if I hover over one, and move off of it, the tooltip moves to the bottom left corner.  If I move across buttons quickly, they populate both in the bottom left corner and stay open over the button

**Comment by lula** [comment]
@w053lxl I can't reproduce it. Tooltips seems just fine to me:

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/614544/71078283-56e05500-2189-11ea-9468-df444edbd5c1.gif)

Can it be related to summernote itself? Have you tried the same with summernote only (I mean without this lib)?

**Comment by w053lxl** [comment]
I use summernote outside of angular in another site and it works just fine.   What version of bootstrap are you running?

**Comment by lula** [comment]
I'm not using bootstrap.

**Comment by w053lxl** [comment]
Okay - well should anyone else come across this -- if you are using Bootstrap 4, you need to reference summernote-bs4.js and summernote-bs4.css in your angular.json instead of summernote-lite.js and summernote-lite.css

**Comment by lula** [comment]
I'll try to have a look at it during my holidays, as I'm quite busy in this period with my work (regular work 😄). 

To make it easier for me, would it be possible for you to share a plunkr or stackblitz?

Thanks!

**Comment by rob-alem** [comment]
I'm experiencing the same issue. @w053lxl 's work-around didn't work for me because I'm not using bootstrap.

**Comment by w053lxl** [comment]
I spent some time this morning trying to get something on stackblitz, but kept running into problems with the implementation of jquery and it thinking $ was not declared (which it was) -  We are using Bootstrap 4, so after reading on summernotes website - 

> For bootstrap 4
> You can also use Summernote with Bootstrap 4 using summernote-bs4.js and summernote-bs4.css. This is also beta version, as Bootstrap 4 is in beta. Below is a code example using bootstrap 4.

I just changed my angular.json file to read summernote-bs4.js and summernote-bs4.css instead of the summernote-lite.bs/css and it resolved our problem.

**Comment by lula** [comment]
Well I was too quick to answer before... too busy too many thoughts... you already said it was working with the "non-lite" summernote! Wonderful! Have wonderful holidays
