### ISSUE TITLE
ERROR TypeError: _this._$element.summernote is not a function

### ISSUE THREAD

**Issue by Jai-Kumaresh** [lula/ngx-summernote#7]
I have error `ERROR TypeError: _this._$element.summernote is not a function` in

Installation
Install ngx-summernote and dependencies:

npm install --save summernote ngx-summernote

Editor
Add add JQuery and Summernote scripts and styles in angular.json file:

"styles": [
	...
	"node_modules/summernote/dist/summernote-lite.css"
],
"scripts": [
	...
	"node_modules/jquery/dist/jquery.min.js",
	"node_modules/summernote/dist/summernote-lite.js"
]
Use [ngxSummernote] directive on an element to init Summernote editor:

`<div [ngxSummernote]></div>`

**Comment by lula** [comment]
Closing

**Comment by srinivasdhuddu** [comment]
we added but the issue still coming

**Comment by suhailkc** [comment]
I have same issue. Is there any solution???

**Comment by msalmankarim** [comment]
I am facing the same issue. jquery is already added. I am using angular 9. Any solution?
