### ISSUE TITLE
ERROR TypeError: _this._$element.summernote is not a function

### ISSUE THREAD

**Issue by suhailkc** [lula/ngx-summernote#71]
I have error ERROR `TypeError: _this._$element.summernote is not a function` in

Installation
Install ngx-summernote and dependencies:

`npm install --save summernote ngx-summernote`

Editor
Add add JQuery and Summernote scripts and styles in angular.json file:

```
"styles": [
...
"node_modules/summernote/dist/summernote-lite.css"
],
"scripts": [
...
"node_modules/jquery/dist/jquery.min.js",
"node_modules/summernote/dist/summernote-lite.js"
]
```
Use [ngxSummernote] directive on an element to init Summernote editor:

`<div [ngxSummernote]></div>`

**Comment by mounthorse-slns** [comment]
Exactly same issue here. I've added:
`'jquery'`
`'ngx-summernote'`
`'summernote'`
`'summernote/dist/summernote-lite.css'`

to my `webpack.config.vendor` file but I got the error:

> TypeError: _this._$element.summernote is not a function

How could I solve this?

**Comment by lula** [comment]
I can't reproduce it. Can you create a plunkr (or similar) so that I can easily check? Thanks

**Comment by mounthorse-slns** [comment]
I'm trying to create a StackBlitzto reproduce the problem. I've encoutered another error:

> $ is not defined
    at new NgxSummernoteDirective

The StackBlitz is here -> https://stackblitz.com/edit/angular-summernote-demo

@lula could you check this?

Thank you very much!

**Comment by lula** [comment]
Well, stackblitz seems to have some problems with bundling the app... The  same app works fine with a fresh new angular project. Try with this [this](https://github.com/lula/ngx-summernote-example)

**Comment by mounthorse-slns** [comment]
@lula Yeah, with your fresh angular-cli project it works but I can't reproduce the error with webpack. I'm not on a simple angular-cli project but on a .NET Core 2 project with webpack and angular.
This project has been generated with the first integration by Microsoft.
Is that the problem, maybe?

**Comment by lula** [comment]
@mounthorse-slns so you have a frontend built with .NET and angular together? And you want to bundle them all together with webpack? I don't really know .NET (nor I ever worked with it nor I am a fan of it :)), so I'm not completely sure what I'm saying can fit but in the end angular bundle is a set of files (js, css) added to the html page, and you could probably build the angular app standalone and just add js to your index.html file (Angular is made for one page app).

**Comment by mounthorse-slns** [comment]
@lula Yes it's as you said. Visual studio offers the possibility (through its wizard) to create a .NET Angular project: Angular for the frontend part and .NET Core for the rest.
Now 
I've noticed that now the VS wizard generate an angular-cli project directly so I suppose that I only have an old version of the structure that it's clearly incompatible with your plugin or need some more configurations that I don't know ;)

**Comment by lula** [comment]
@mounthorse-slns jquery is not found, therefore you have the error. What if you explicitly try to add jquery to your index.html file? Something like in [here](https://codeburst.io/how-to-use-webpack-in-asp-net-core-projects-a-basic-react-template-sample-25a3681a5fc2).

**Comment by lula** [comment]
yeah well eheh I didn't went over the Introducing JQuery to the solution part. So perhaps addind explicitly jquery may not be the right solution. Going further with the blog there are other leads you may follow. Most likely you have already try them all but never say never :)

**Comment by mounthorse-slns** [comment]
@lula thank you for you advices. I've already configure the application to work with angular and webpack :) I've started writing here because of the problem of the first post.
For the rest, jquery works well in my solutions :)

**Comment by lula** [comment]
@mounthorse-slns I've reported the bug to stackblitz. Others seem to have the same problem [https://github.com/stackblitz/core/issues/700](https://github.com/stackblitz/core/issues/700)

**Comment by lula** [comment]
The issue still persist in stackblitz (ignoring angular.json) but at least the demo project works in stackblitz now 🎉 

[https://stackblitz.com/edit/angular-summernote-demo-zwzcyj](https://stackblitz.com/edit/angular-summernote-demo-zwzcyj)

Version 0.7.6 is released with some of the changes done to make the demo work in stackblitz. Changes are related to summernote element initialization, now done only when jquery is loaded.

🙏 Many thanks to @dev-sharan for stackblitz workaround and @stephanrauh for spending his time to point me to the timing problem. You guys rock 🙌 !

**Comment by mounthorse-slns** [comment]
@lula Thank you for your answer. I've tried your stackblitz demo and I see that it works!
I've applied your solution to my project but still dowsn't work. At this point I think that it's due to the old project structure. Is that possible?

**Comment by lula** [comment]
@mounthorse-slns have you tried to use the latest version of ngx-summernote? Can you perhaps share your project or at least a repo that I can clone and test with?

**Comment by mounthorse-slns** [comment]
Hi @lula ...Sorry for the later response, however I've tried again with the new version (`0.7.7`) and the same issue occurs:

> ERROR TypeError: _this._$element.summernote is not a function
    at vendor.js?v=F_NGhtptsWze8Xw6SjZx7n2SX9JO8VYre7sG_z5E4Zo:200816
    at ZoneDelegate.invoke (vendor.js?v=F_NGhtptsWze8Xw6SjZx7n2SX9JO8VYre7sG_z5E4Zo:213529)
    at Zone.run (vendor.js?v=F_NGhtptsWze8Xw6SjZx7n2SX9JO8VYre7sG_z5E4Zo:213288)
    at NgZone.runOutsideAngular (vendor.js?v=F_NGhtptsWze8Xw6SjZx7n2SX9JO8VYre7sG_z5E4Zo:27041)
    at NgxSummernoteDirective.createEditor (vendor.js?v=F_NGhtptsWze8Xw6SjZx7n2SX9JO8VYre7sG_z5E4Zo:200811)
    at NgxSummernoteDirective.ngOnInit (vendor.js?v=F_NGhtptsWze8Xw6SjZx7n2SX9JO8VYre7sG_z5E4Zo:200556)
    at checkAndUpdateDirectiveInline (vendor.js?v=F_NGhtptsWze8Xw6SjZx7n2SX9JO8VYre7sG_z5E4Zo:21923)
    at checkAndUpdateNodeInline (vendor.js?v=F_NGhtptsWze8Xw6SjZx7n2SX9JO8VYre7sG_z5E4Zo:30321)
    at checkAndUpdateNode (vendor.js?v=F_NGhtptsWze8Xw6SjZx7n2SX9JO8VYre7sG_z5E4Zo:30283)
    at debugCheckAndUpdateNode (vendor.js?v=F_NGhtptsWze8Xw6SjZx7n2SX9JO8VYre7sG_z5E4Zo:30917)

I'll try to make a lite version to test with.

**Comment by mounthorse-slns** [comment]
@lula I've pushed a lite version to reproduce the issues.
You can find the repo here: https://github.com/mounthorse-slns/public-test

Let me know :)
