### ISSUE TITLE
Add button in summer note to copy and paste html content

### ISSUE THREAD

**Issue by dhavalsolankislk** [lula/ngx-summernote#74]
Hello, 
We are using summernote. We want a functionality to copy and paste html content in summernote. We are achieving this functionality through html jquery. But in our application we are not using jquery. So do we have any option to add custom button using angular.

**Comment by lula** [comment]
Hello @dhavalsolankislk see in the [readme](https://github.com/lula/ngx-summernote#add-custom-button) how to add custom buttons
