### ISSUE TITLE
New version summernote (new resources)

### ISSUE THREAD

**Issue by MaurilioDeveloper** [lula/ngx-summernote#75]
Hello,
We are using the summernote, and we would like to implement the new version that was released, currently, these features have the buttons with 'Blockquote' and all the 'HEADERS' (H1, H2, H3, H4, H5, H6). 
How can I put these new buttons on my summernote using your library?
Will you realease a new updated version? Or Could you please help me to add these funcionalities?
Thanks.

**Comment by lula** [comment]
Hi @MaurilioDeveloper you may try to update the npm summernote package to the latest version (0.8.15). I haven't tried already to test it but you may try and see if it's working.

**Comment by tim-boerner** [comment]
0.8.15 is working with this library, i updated.
Unfortunately airMode is broken ([issue - 3588](https://github.com/summernote/summernote/issues/3588))

**Comment by lula** [comment]
@tim-boerner thanks! Let's wait for a bug fix from on summernote lib. I'm leaving this open as a reminder.

**Comment by lula** [comment]
I retested and airMode seem to work just fine.
