### ISSUE TITLE
Default font size not taking in summer note

### ISSUE THREAD

**Issue by dhavalsolankislk** [lula/ngx-summernote#79]
Hello,
We are using summer note in our application. We are facing a issue that when we are setting default font size to 14px in configuration it is not taking default font size 14 in drop down as default selected font size. After clicking on editable area, font size drop down value is changed to 14px automatically.

**Comment by lula** [comment]
Hello @dhavalsolankislk see [2879](https://github.com/summernote/summernote/issues/2879)
