### ISSUE TITLE
ERROR in ./src/app/app.module.ts Module not found: Error: Can't resolve '/opt/lampp/htdocs/ngx-summernote/dist/ngx-summernote' in '/opt/lampp/htdocs/ngx-summernote/src/app'

### ISSUE THREAD

**Issue by Jai-Kumaresh** [lula/ngx-summernote#8]
Your soruse code(https://github.com/lula/ngx-summernote) not work for me. My error is
`ERROR in ./src/app/app.module.ts Module not found: Error: Can't resolve '/opt/lampp/htdocs/ngx-summernote/dist/ngx-summernote' in '/opt/lampp/htdocs/ngx-summernote/src/app'`

**Comment by AnatoliiDev** [comment]
Can I use it with Angular 4?

**Comment by ajaybabum** [comment]
I am also getting same error @lula

**Comment by vuducbinh0110** [comment]
@Jai-Kumaresh @AnatoliiDev @lula 
I met the same error and I tried to figure it out.
There is an issue with the file **tsconfig.json** in the root folder with the path configuration, just need to remove it.

`{
  "compileOnSave": false,
  "compilerOptions": {
    "baseUrl": "./",
    "outDir": "./dist/out-tsc",
    "sourceMap": true,
    "declaration": false,
    "moduleResolution": "node",
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "target": "es5",
    "typeRoots": [
      "node_modules/@types"
    ],
    "lib": [
      "es2017",
      "dom"
    ],
    "paths": {}
  }
}`

Make sure that you have 2 folders ngx-summernote and  summernote in node_modules.
Good luck!
