### ISSUE TITLE
Link is not clickable inside ngx-summernote

### ISSUE THREAD

**Issue by ramitmathur27m** [lula/ngx-summernote#81]
Hi,

I am trying to type link something like

https://www.google.com 
But this is not allowing me to take to different page mainly its not taking me anywhere. It does  showing that its a hyperlink but not taking me anywhere
Please let me know what i can do for this

The Config for summer note which i am using is below: 
**config = {
        height: '200px', width: '100%',
        toolbar: [
            // [groupName, [list of button]]
            ['misc', ['codeview', 'undo', 'redo']],
            ['style', ['bold', 'italic', 'underline', 'clear']],
            ['font', ['strikethrough', 'superscript', 'subscript', 'clear']],
            ['fontsize', ['color']],
            ['para', ['style0', 'ul', 'ol']],
            ['insert', ['table', 'picture', 'link', 'video', 'hr']]
        ],
        popover: {
            image: [],
            link: [],
         air: []
        }
    };**

**Comment by lula** [comment]
Hello @ramitmathur27m  with the lastest summernote I can see something like this:

<img width="323" alt="Screenshot 2020-03-07 at 10 11 39" src="https://user-images.githubusercontent.com/614544/76140561-1f809680-605c-11ea-8ef4-af6702747bd3.png">

Just add link in the popover section like

```
link: [
        ['link', ['linkDialogShow', 'unlink']]
      ]
```

**Comment by ramitmathur27m** [comment]
Thanks Lula, But main thing is when i am retrieving this link like http://www.google.com from backend it never shows clickable until user reach to the end and tap a space. How we can show this as link in re-trivial case. Please help

**Comment by Sarthaktydy** [comment]
Hey, tried using 
`"ngx-summernote": "^0.7.0",
"summernote": "^0.8.16"
`
Still got the same issue can't se any popup for link access
