### ISSUE TITLE
Angular 9 dependencies

### ISSUE THREAD

**Issue by elementalPRESS** [lula/ngx-summernote#84]
Hi there,  really love that editor and the wrapper for Angular. Unfortunately, I get always dependency warnings. In the documentation is written that version 0.7.x supports Angular 9. So I'm a bit confused. Pls, can you check out and fix that problem?

npm WARN ngx-summernote@0.7.6 requires a peer of @angular/common@^8.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN ngx-summernote@0.7.6 requires a peer of @angular/core@^8.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN ngx-summernote@0.7.6 requires a peer of @angular/forms@^8.0.0 but none is installed. You must install peer dependencies yourself.

best regards,
Lars

**Comment by lula** [comment]
Hello Lars, 0.7.7 should resolve those warnings. Cheers
