### ISSUE TITLE
error Can't bind to 'ngxSummernote' since it isn't a known property of 'textarea'. (" 

### ISSUE THREAD

**Issue by guypeled1** [lula/ngx-summernote#9]
this is my code:
  <form action="#" class="editor-form">
    <textarea [ngxSummernote] name="" id="" cols="30" rows="10" class="editor-area" placeholder="Type your answer here..."></textarea>
    <div class="editor-words">
      <span class="editor-words-text">0/200 words</span>
    </div>
  </form>

How can i solve this?

**Comment by FeezyHendrix** [comment]
Did you restart the angular server after you added the files to the angular.json

**Comment by lula** [comment]
Although I'm not sure why you'd want to do that, I just tested it without errors. This sounds like you missed to add NgxSummernoteModule to your app.module.

**Comment by cloudhunterca** [comment]
NgxSummernoteModule does not exist. Can you help

**Comment by cloudhunterca** [comment]
I have figured out that there is a module https://github.com/lula/ngx-summernote/tree/master/projects/ngx-summernote/src/lib.

But I don't know how to use it,

**Comment by igordos** [comment]
import { NgxSummernoteModule } from 'node_modules/ngx-summernote';
Add this line to your app.module.

**Comment by bhatt098** [comment]
facing same kind of issue
Can't bind to 'ngxSummernote' since it isn't a known property of 'div'.

 <div [ngxSummernote]="editorConfig" id="texteditTemplate"></div> 
 NgxSummernoteModule added on app modu;le.ts
