### ISSUE TITLE
Editor with validation

### ISSUE THREAD

**Issue by OmarAlkylaney** [lula/ngx-summernote#91]
I would like to use the summer-note on Angular 9 CLI with required validation. However, its seem to me is not validating. here is an example bellow. It seem to me that's thee is a timing delay between the summer-note and the angular model binding

  `<div [ngxSummernote]="config" name="Description" [(ngModel)]="model.description" maxlength="50"
                               #refDescription="ngModel" id="newsDescription" required></div>                      
                        <div *ngIf="!refDescription.valid  && (refDescription.dirty || refDescription.touched)" class="alert alert-danger">
                            <div [hidden]="!refDescription.errors.required">
                                News Description is required
                            </div>
                        </div>`

Thanks,
Omar

![SummernoteValidation](https://user-images.githubusercontent.com/35583003/84974818-5855fe80-b167-11ea-801a-76398d468125.png)

**Comment by OmarAlkylaney** [comment]
Hi All,

Its turned out only when you highlighted the text and press backspace or delete. It will note trigger the validations. if you do backspace letter by letter. It will trigger the validations. 
![SummernoteValidation](https://user-images.githubusercontent.com/35583003/84983490-3fa41380-b17c-11ea-8c71-e4ff0ae74d23.png)
![SummernoteValidationFired](https://user-images.githubusercontent.com/35583003/84983493-40d54080-b17c-11ea-9585-dead95e38e39.png)

**Comment by lula** [comment]
Hello Omar! Sorry, I don't get your point. I just committed in the example application required validators for html property

[component controller](https://github.com/lula/ngx-summernote/blob/797fb40d425422329ede98f1394ee6b3c528c999/src/app/app.component.ts#L82)

[html](https://github.com/lula/ngx-summernote/blob/797fb40d425422329ede98f1394ee6b3c528c999/src/app/app.component.html#L23)

Everything seems to work for me. Could you please check?

**Comment by OmarAlkylaney** [comment]
Hi Lula,

The issue is the Text Editor validating normally once you do back spaces to the editor. However, It is not validating when you highlight say the whole text and press delete or backspaces. Furthermore, it will be not validating once you enter the editor (Focus on the editor) and then click outside. Hope this explain more :)

**Comment by OmarAlkylaney** [comment]
Here is my code for your reference 

`
<div class="row">
    <div class="col-lg-12">
        <h1 class="page-header">News</h1>
    </div>
    
</div>

<div class="panel panel-default">
    <div class="panel-heading">Add News</div>
    <div class="panel-body">
        <form #form="ngForm" novalidate (ngSubmit)="onSubmit()">
            <div class="row">
                <div class="col-md-6">
                    <div class="form-group">
                        <label for="newsTitle">Title</label>
                        <input type="text" class="form-control" name="Title" [(ngModel)]="newsModel.title" maxlength="50"
                               #refTitle="ngModel" id="newsTitle" required>
                        <div *ngIf="!refTitle.valid  && (refTitle.dirty || refTitle.touched)" class="alert alert-danger">
                            <div [hidden]="!refTitle.errors.required">
                                News Title is required
                            </div>
                        </div>
                    </div>

                    <div class="form-group">
                        <label for="newsDescription">Title</label>
                        <div [ngxSummernote]="config" name="Description" [(ngModel)]="newsModel.description" maxlength="50"
                               #refDescription="ngModel" id="newsDescription" required></div>                      
                        <div *ngIf="!refDescription.valid  && (refDescription.dirty || refDescription.touched)" class="alert alert-danger">
                            <div [hidden]="!refDescription.errors.required">
                                News Description is required
                            </div>
                        </div>
                    </div>

                    <div class="form-group">
                        <button type="submit" swIsLoading='loading-progress' style="margin-top: 10px" [disabled]="!form.form.valid" class="btn btn-success">Submit</button>
                        <a style="margin-left: 10px; margin-top:7px;" class="btn btn-info" [routerLink]="['/news/all']">
                            All News
                        </a>
                    </div>
                    <div #alert *ngIf="errorMessage.length > 0" class="alert alert-danger alert-dismissible show" role="alert">
                        <button type="button" class="close" aria-label="Close" (click)="closeAlert()">
                            <span aria-hidden="true">&times;</span>
                        </button>
                        {{errorMessage}}
                    </div>

                </div>
            </div>
        </form>
    </div>
</div>


import { Component, OnInit, ViewChild, ElementRef } from '@angular/core';
import { News } from '../Models/news';
import { NewsService } from './Services/news.service';
import { Router } from '@angular/router';
import { IsLoadingService } from '@service-work/is-loading';
declare var $: any;
@Component({
  selector: 'app-add-news',
  templateUrl: './add-news.component.html',
  styleUrls: ['./add-news.component.less']
})
export class AddNewsComponent implements OnInit {
  newsModel: News = new News();
  private _newsService;
  title = 'Add News';
  output: any;
  errorMessage: string = '';
  @ViewChild('alert', { static: false }) alert: ElementRef;
  @ViewChild('refDescription', { read: ElementRef, static: true }) refDescription: ElementRef;
  @ViewChild('form', { static: false }) form: any;

  public self = this;
  config = {
    placeholder: 'Add news description',
    tabsize: 2,
    height: '200px',
    codeviewFilter: true,
    codeviewIframeFilter: true,
    callbacks: {
      onChange: function (contents, $editable) {
        //console.log('onChange:', contents, $editable);
      }
    },
    toolbar: [
      ['misc', ['codeview', 'undo', 'redo']],
      ['style', ['bold', 'italic', 'underline', 'clear']],
      ['font', ['bold', 'italic', 'underline', 'strikethrough', 'superscript', 'subscript', 'clear']],
      ['fontsize', ['fontname', 'fontsize', 'color']],
      ['para', ['style', 'ul', 'ol', 'paragraph', 'height']],
      ['insert', ['table', 'link', 'hr']]
    ],
    fontNames: ['Helvetica', 'Arial', 'Arial Black', 'Comic Sans MS', 'Courier New', 'Roboto', 'Times']
  }

  constructor(private _route: Router, private _isLoadingService: IsLoadingService, newsService: NewsService) {
    this._newsService = newsService;
  }

  ngOnInit(): void {
  }



  //Close the alert box
  closeAlert() {
    this.alert.nativeElement.classList.add('hidden');
  }

  onSubmit() {
    this._isLoadingService.add({ key: ['default', 'updating-data'] });
    this._isLoadingService.add(
      this._newsService.addNews(this.newsModel).subscribe(
        response => {
          this._isLoadingService.remove({ key: ['default', 'updating-data'] });
          this.output = response
          if (this.output.statusCode == "409") {
            this.errorMessage = this.output.content.value;
          }
          else if (this.output.statusCode == "200") {
            alert('Job Tag Saved Successfully');
            this._route.navigate(['/news/all']);
          }
          else {
            this.errorMessage = "Something Went Wrong, Please try again later";
          }
        }), { key: 'loading-progress' }
    );
  }

}
`

**Comment by OmarAlkylaney** [comment]
I got it why. The reason for that is when you highlight the text and remove it via the backspace or the delete. The model will be bind to <p><br></p> and not an empty string and hence the required field will be valid. 


![SummernoteValdation](https://user-images.githubusercontent.com/35583003/85095567-1bf0d400-b235-11ea-8668-5996bb6fd4ad.png)

**Comment by lula** [comment]
From what I see, deletion actually leaves some html. Therefore, it seems related to [this](https://github.com/lula/ngx-summernote/issues/89) I think. I guess this is more an issue to address to summernote.

**Comment by OmarAlkylaney** [comment]
Hi Lula,

I will try to add pattern validator to validate the editor once it matches the above HTML Tags

**Comment by OmarAlkylaney** [comment]
Hi Lula,

I tried to use the pattern validation and its not validating with pattern. I try with an input and its validating it correctly. Please note I am using PatternValidator directive and not with  formControl

**Comment by OmarAlkylaney** [comment]
I have make it working by changing the html tag to text area instead of div due it will be not binding the validator pattern with the div

**Comment by swanand6300** [comment]
> Hello Omar! Sorry, I don't get your point. I just committed in the example application required validators for html property
> 
> [component controller](https://github.com/lula/ngx-summernote/blob/797fb40d425422329ede98f1394ee6b3c528c999/src/app/app.component.ts#L82)
> 
> [html](https://github.com/lula/ngx-summernote/blob/797fb40d425422329ede98f1394ee6b3c528c999/src/app/app.component.html#L23)
> 
> Everything seems to work for me. Could you please check?

Try Adding values with formatting and then Select all and delete the content. The validation is not working in this case
