### ISSUE TITLE
Compatibility with Angular 10

### ISSUE THREAD

**Issue by Pocciox** [lula/ngx-summernote#95]
Hi,
I was trying to update my project that uses ngx-summernote to angular 10, but I got this errors when running the command:

ng update @angular/core @angular/cli

Installing packages for tooling via npm.
Installed packages for tooling via npm.
Using package manager: 'npm'
Collecting installed dependencies...
Found 48 dependencies.
Fetching dependency metadata from registry...
                  Package "ngx-summernote" has an incompatible peer dependency to "@angular/core" (requires "^8.0.0" (extended), would install "10.0.4").
                  Package "ngx-summernote" has an incompatible peer dependency to "@angular/common" (requires "^8.0.0" (extended), would install "10.0.4").
                  Package "ngx-summernote" has an incompatible peer dependency to "@angular/forms" (requires "^8.0.0" (extended), would install "10.0.4").
✖ Migration failed: Incompatible peer dependencies found.
Peer dependency warnings when installing dependencies means that those dependencies might not work correctly together.
You can use the '--force' option to ignore incompatible peer dependencies and instead address these warnings later.
  See "/tmp/ng-GQqdYS/angular-errors.log" for further details.

Should i use the --force option, or should i wait for an updated relase of ngx-summernote that is compatible with angular 10?
If needed i can try my best to make it work with angular 10 myself and provide a working pull request.
Thanks!

**Comment by tribe84** [comment]
Having the same issue, cannot upgrade to Angular 10 because of this lib.

Is this repo dead?

**Comment by lula** [comment]
Hello everybody! Repo is not dead, but I had work to sort out and then I was on vacation (this month). 

So, I have no problem, generally speaking, with angular 10, I'm actually using ngx-summernote in angular 10 projects. Please try to install latest version (0.7.8), the project package.json should be updated to support angular 10.

**Comment by tribe84** [comment]
Thanks!

**Comment by LuigiElleBalotta** [comment]
@lula check this pr #99

**Comment by BehnamAbdy** [comment]
nevermind the compatibility issue and install it with npm --force command, for me it worked

**Comment by lula** [comment]
I believe this can be closed.
